### ISSUE TITLE
Redundant compilation causes Handlebars error

### ISSUE THREAD

**Issue by JHKennedy4** [mulderp/generator-backbone-browserify#1]
I believe that having hbsfy listed as a transform and manually calling it in the makefile is causing a redundant compilation to occur which results in handlbars spitting out the hbsfy code as a template. Removing hbsfy from the list of transforms solved the problem for me.

**Comment by mulderp** [comment]
Interesting - the result without the hbsy transform looks good indeed. I'll need to check why I had the hbsy transform in the first place. I'll try to clean this up. Thanks for the notice.

**Comment by mulderp** [comment]
indeeed, the hbsy transform is done via the package.json - I've cleaned the repo up.
Thanks again for your feedback; by the way, with some minor tweaks the generator works also for Handlebones (see https://github.com/FormidableLabs/handlebones )

**Comment by JHKennedy4** [comment]
Thanks for the great generator.
